### ISSUE TITLE
be more relaxed on the array of valid values ?

### ISSUE THREAD

**Issue by er314** [SandroMiguel/verum-php#2]
Hi, thank you for this neat validation library.
Could you allow more relaxed array of valid values for the CONTAINS rule ?
eg. arrays with index not starting at 0, or associative arrays
-> maybe by replacing :
`if (!isset($this->ruleValues[0]))`
with : 
`if (empty($this->ruleValues))`

My aim is the CONTAINS rule, but I guess this remark applies to all the rules which take an array as argument.
thanks

**Comment by SandroMiguel** [comment]
Hi @er314 
I'm not sure if I should allow a more relaxed array of valid values.
I'm also not sure about accepting associative arrays. I think that the accepted structure should be as simple as possible. If you have am associative array with a set of valid values, you can flatten them first and pass the indexed array to the library.

**Comment by er314** [comment]
Agreed of course that formatting the array towards the current expectation means only 1 extra line of code.
It's just that forcing an array as currently (= forcing it to start at internal index 0) seems a bit "overkill" to me 
(it was a surprise at first, trying to understand what was wrong with my rules structure - that's because in my processing I unset some array entries before using this array in the rule definition).
Anyway, it doesn't really matter.
thanks
