### ISSUE TITLE
REGEX rule error if fieldValue is null

### ISSUE THREAD

**Issue by er314** [SandroMiguel/verum-php#8]
If the REGEX rule is executed on a null fieldValue, then it fails, due to preg_match not expecting null data.
I don't know if this is the expected behavior for the rule, 
but anyway this can be fixed eg. by adding the following at the beginning of the validate() method : 
```
            if (!is_string($this->fieldValue)) {
                return false;
            }

```

**Comment by SandroMiguel** [comment]
Hey @er314, you're right, this is a bug. Thank you for reporting!

**Comment by er314** [comment]
note : fixed as part of pull request https://github.com/SandroMiguel/verum-php/pull/9
